spring:
  datasource:
    url: jdbc:h2:tcp://localhost/C:/Users/user/Desktop/studyDB/h2_prac/datajpa_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true   # 콘솔에 SQL 출력 원할 경우 주석 해제
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace   # 파라미터 바인딩 값까지 로그 출력 시 주석 해제
